version: '3.8'

services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  # db is is db folder
  db:
    build: db/.
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: employees
      MYSQL_ROOT_HOST: '%'
    ports:
      - "33060:3306"

  # Web Dockerfile is in web folder .
  web:
    build: web/.
    ports:
      - "80:80"
    depends_on:
      - app