blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a question
    url: https://github.com/moe-arkarlwin/Global_World_Population/discussions
    about: Ask a general question about the project
