name: A workflow for my Global World Population App
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 24
        uses: actions/setup-java@v2
        with:
          java-version: '24'
          distribution: 'adopt'
      - name: Unit Tests
        run: mvn -Dtest=com.globalworldpopulation.MySQL_Test_Unit_Test test
      - name: CodeCov
        uses: codecov/codecov-action@v5
        with:
          #token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./target/site/jacoco
          flags: Unit Tests # optional
          verbose: true # optional (default = false)

  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 24
        uses: actions/setup-java@v2
        with:
          java-version: '24'
          distribution: 'adopt'
      - name: Integration Tests
        run: |
          docker compose up -d db
          mvn -Dtest=com.globalworldpopulation.MySQL_Test_Integration_Test test
      - name: Shutdown
        run: docker compose down
      - name: CodeCov
        uses: codecov/codecov-action@v5
        with:
          #token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./target/site/jacoco
          flags: Integration Tests # optional
          verbose: true # optional (default = false)

  build:
    name: Build Run in Docker and Deploy Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 24
        uses: actions/setup-java@v2
        with:
          java-version: '24'
          distribution: 'adopt'
      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            ./target/*.jar

#  build:
#    name: Build and Start Using docker-compose
#    runs-on: ubuntu-24.04
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#        with:
#          submodules: recursive
#      - name: Set up JDK 24
#        uses: actions/setup-java@v2
#        with:
#          java-version: '24'
#          distribution: 'adopt'
#      - name: Setup network
#        run: |
#            docker network create --driver bridge globalworldpopulation
#            docker pull mongo
#            docker run -d --name mongo-dbserver --network globalworldpopulation mongo
#      - name: Build with Maven
#        run: mvn package
#      - name: Run docker compose
#        run: docker compose up --abort-on-container-exit
#      - name: Build
#        run: docker build -t worldpopulation .
#      - name: Run image
#        run: docker run --network globalworldpopulation --name devopscontainer worldpopulation
#      - name: view logs
#        run: docker logs devopscontainer
#      - name: Unit Tests
#        run: mvn -Dtest=com.globalworldpopulation.MySQL_Test_Unit_Test test
#     - name: Package and Run docker compose
#        run: |
#            mvn package -DskipTests
#            docker compose up --abort-on-container-exit
