name: A workflow for my Global World Population App
on: push

permissions:
  contents: write

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 24
        uses: actions/setup-java@v2
        with:
          java-version: '24'
          distribution: 'adopt'
      - name: Unit Tests
        run: mvn -Dtest=com.globalworldpopulation.MySQL_Test_Unit_Test test
      - name: CodeCov
        uses: codecov/codecov-action@v5
        with:
          #token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./target/site/jacoco
          flags: Unit Tests # optional
          verbose: true # optional (default = false)

  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 24
        uses: actions/setup-java@v2
        with:
          java-version: '24'
          distribution: 'adopt'
      - name: Integration Tests
        run: |
          docker compose up -d db
          mvn -Dtest=com.globalworldpopulation.MySQL_Test_Integration_Test test
      - name: Shutdown
        run: docker compose down
      - name: CodeCov
        uses: codecov/codecov-action@v5
        with:
          #token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./target/site/jacoco
          flags: Integration Tests # optional
          verbose: true # optional (default = false)

  build:
    name: Build Run in Docker and Deploy Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 24
        uses: actions/setup-java@v2
        with:
          java-version: '24'
          distribution: 'adopt'
      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit
      - name: Copy Output
        run: docker container cp global_world_population-app-1:./tmp/reports ./
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: reports # The branch the action should deploy to.
          folder: reports # The folder we are copying
